"""add aura economy

Revision ID: 07e92ba04dd5
Revises: deda66258b96
Create Date: 2026-08-31 12:42:24.980405

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "07e92ba04dd5"
down_revision: str | None = "deda66258b96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economy_accounts",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("wallet", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("bank", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("lifetime_earned", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("last_message_reward_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("bank >= 0", name=op.f("ck_economy_accounts_bank_non_negative")),
        sa.CheckConstraint("wallet >= 0", name=op.f("ck_economy_accounts_wallet_non_negative")),
        sa.PrimaryKeyConstraint("guild_id", "user_id", name=op.f("pk_economy_accounts")),
    )
    with op.batch_alter_table("economy_accounts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_economy_accounts_guild_wallet_bank", ["guild_id", "wallet", "bank"], unique=False
        )

    op.create_table(
        "economy_role_purchases",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("price_paid", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "guild_id", "user_id", "role_id", name=op.f("pk_economy_role_purchases")
        ),
    )
    op.create_table(
        "economy_role_rewards",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_economy_role_rewards_price_non_negative")),
        sa.PrimaryKeyConstraint("guild_id", "role_id", name=op.f("pk_economy_role_rewards")),
        sa.UniqueConstraint("guild_id", "tier", name="one_role_per_tier"),
    )
    op.create_table(
        "economy_settings",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("voice_aura_per_minute", sa.Integer(), server_default="1", nullable=False),
        sa.Column("message_aura", sa.Integer(), server_default="2", nullable=False),
        sa.Column("message_cooldown_seconds", sa.Integer(), server_default="60", nullable=False),
        sa.Column("deposit_fee_percent", sa.Integer(), server_default="5", nullable=False),
        sa.Column("min_voice_humans", sa.Integer(), server_default="2", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("guild_id", name=op.f("pk_economy_settings")),
    )
    op.create_table(
        "economy_transactions",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("wallet_after", sa.BigInteger(), nullable=False),
        sa.Column("bank_after", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_economy_transactions")),
    )
    with op.batch_alter_table("economy_transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_economy_transactions_guild_user_created",
            ["guild_id", "user_id", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("economy_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_economy_transactions_guild_user_created")

    op.drop_table("economy_transactions")
    op.drop_table("economy_settings")
    op.drop_table("economy_role_rewards")
    op.drop_table("economy_role_purchases")
    with op.batch_alter_table("economy_accounts", schema=None) as batch_op:
        batch_op.drop_index("ix_economy_accounts_guild_wallet_bank")

    op.drop_table("economy_accounts")
    # ### end Alembic commands ###
