"""add work cooldowns lottery and betting limits

Revision ID: 805b220b989f
Revises: 07e92ba04dd5
Create Date: 2026-08-31 13:02:31.849678

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "805b220b989f"
down_revision: str | None = "07e92ba04dd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economy_cooldowns",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("guild_id", "user_id", "key", name=op.f("pk_economy_cooldowns")),
    )
    op.create_table(
        "economy_lottery_state",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("pot", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("last_draw_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("pot >= 0", name=op.f("ck_economy_lottery_state_pot_non_negative")),
        sa.PrimaryKeyConstraint("guild_id", name=op.f("pk_economy_lottery_state")),
    )
    op.create_table(
        "economy_lottery_tickets",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("tickets", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("tickets > 0", name=op.f("ck_economy_lottery_tickets_tickets_positive")),
        sa.PrimaryKeyConstraint("guild_id", "user_id", name=op.f("pk_economy_lottery_tickets")),
    )
    with op.batch_alter_table("economy_accounts", schema=None) as batch_op:
        batch_op.drop_column("last_message_reward_at")

    with op.batch_alter_table("economy_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("work_min", sa.Integer(), server_default="100", nullable=False)
        )
        batch_op.add_column(
            sa.Column("work_max", sa.Integer(), server_default="200", nullable=False)
        )
        batch_op.add_column(
            sa.Column("work_cooldown_seconds", sa.Integer(), server_default="86400", nullable=False)
        )
        batch_op.add_column(sa.Column("min_bet", sa.Integer(), server_default="10", nullable=False))
        batch_op.add_column(
            sa.Column("max_bet", sa.BigInteger(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column("lottery_ticket_price", sa.Integer(), server_default="100", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("economy_settings", schema=None) as batch_op:
        batch_op.drop_column("lottery_ticket_price")
        batch_op.drop_column("max_bet")
        batch_op.drop_column("min_bet")
        batch_op.drop_column("work_cooldown_seconds")
        batch_op.drop_column("work_max")
        batch_op.drop_column("work_min")

    with op.batch_alter_table("economy_accounts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_message_reward_at",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            )
        )

    op.drop_table("economy_lottery_tickets")
    op.drop_table("economy_lottery_state")
    op.drop_table("economy_cooldowns")
    # ### end Alembic commands ###
