"""initial schema

Revision ID: 85b653ce39cb
Revises:
Create Date: 2026-08-30 17:21:12.194687

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "85b653ce39cb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_invocations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("command", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_command_invocations")),
    )
    with op.batch_alter_table("command_invocations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_command_invocations_command_created_at", ["command", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("command_invocations", schema=None) as batch_op:
        batch_op.drop_index("ix_command_invocations_command_created_at")

    op.drop_table("command_invocations")
    # ### end Alembic commands ###
