"""add per-guild cog enablement

Revision ID: deda66258b96
Revises: b3b6c49ed144
Create Date: 2026-08-31 12:14:04.558970

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "deda66258b96"
down_revision: str | None = "b3b6c49ed144"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_cogs",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("cog", sa.String(length=100), nullable=False),
        sa.Column("enabled_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("guild_id", "cog", name=op.f("pk_guild_cogs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guild_cogs")
    # ### end Alembic commands ###
